In [1]:
from scipy.sparse import *
import pandas as pd
import numpy as np
from sample import sample_generator

In [4]:
rng = sample_generator(3, 1000)

In [93]:
print(rng.X.to_latex())

\begin{tabular}{lrrr}
\toprule
{} &  X1 &  X2 &  X3 \\
\midrule
0   &   0 &   1 &   0 \\
1   &   0 &   1 &   0 \\
2   &   0 &   1 &   0 \\
3   &   1 &   1 &   0 \\
4   &   1 &   1 &   0 \\
5   &   1 &   1 &   1 \\
6   &   1 &   1 &   1 \\
7   &   1 &   1 &   0 \\
8   &   0 &   0 &   0 \\
9   &   0 &   1 &   1 \\
10  &   1 &   1 &   0 \\
11  &   0 &   1 &   0 \\
12  &   1 &   1 &   0 \\
13  &   1 &   1 &   0 \\
14  &   1 &   1 &   0 \\
15  &   1 &   1 &   1 \\
16  &   0 &   1 &   0 \\
17  &   0 &   1 &   0 \\
18  &   1 &   0 &   0 \\
19  &   1 &   0 &   0 \\
20  &   1 &   1 &   1 \\
21  &   1 &   0 &   0 \\
22  &   0 &   1 &   0 \\
23  &   1 &   0 &   0 \\
24  &   1 &   1 &   0 \\
25  &   0 &   0 &   0 \\
26  &   1 &   1 &   0 \\
27  &   0 &   1 &   1 \\
28  &   1 &   0 &   0 \\
29  &   1 &   1 &   1 \\
30  &   1 &   1 &   1 \\
31  &   1 &   1 &   0 \\
32  &   1 &   1 &   1 \\
33  &   1 &   1 &   0 \\
34  &   0 &   1 &   0 \\
35  &   1 &   1 &   0 \\
36  &   1 &   0 &   0 \\
37  &   0 &

/var/folders/xj/07knx1_11gl5w1nv4tg4xr000000gn/T/ipykernel_5110/3272998563.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(rng.X.to_latex())


In [6]:
rng.barcode

array([[2],
       [2],
       [2],
       [6],
       [6],
       [7],
       [7],
       [6],
       [0],
       [3],
       [6],
       [2],
       [6],
       [6],
       [6],
       [7],
       [2],
       [2],
       [4],
       [4],
       [7],
       [4],
       [2],
       [4],
       [6],
       [0],
       [6],
       [3],
       [4],
       [7],
       [7],
       [6],
       [7],
       [6],
       [2],
       [6],
       [4],
       [2],
       [4],
       [4],
       [4],
       [3],
       [1],
       [3],
       [6],
       [6],
       [6],
       [2],
       [6],
       [5],
       [2],
       [2],
       [6],
       [6],
       [4],
       [2],
       [7],
       [6],
       [2],
       [7],
       [0],
       [1],
       [7],
       [7],
       [5],
       [4],
       [7],
       [3],
       [4],
       [6],
       [2],
       [7],
       [6],
       [2],
       [6],
       [3],
       [4],
       [2],
       [7],
       [2],
       [6],
       [6],
       [7],
    

In [8]:
P = 2**rng.p

In [24]:
rows_dict = {i: np.argwhere(rng.barcode.reshape(-1) == i).reshape(-1) for i in range(P)}
ones = {i: np.array([1 for _ in range(len(arr))]) for i,arr in rows_dict.items()}
N = rng.X.shape[0]

In [28]:
ones[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
rows_dict[0]

array([  8,  25,  60,  99, 152, 169, 187, 264, 270, 343, 358, 410, 432,
       442, 492, 494, 496, 510, 570, 572, 581, 608, 614, 631, 670, 672,
       675, 693, 709, 768, 821, 893, 909, 913, 928, 937, 968, 986])

In [57]:
def gen_crs_arr(val):
    rows = rows_dict[val]
    one = ones[val]
    array = csc_matrix((one, ([0 for _ in range(len(rows))], rows)), shape = (1, N))
    return array

In [65]:
def gen_connectivity_matrix(barcode):
    crs_arrays = []
    for b in rng.barcode.reshape(-1):
        array = gen_crs_arr(b)
        crs_arrays.append(array)
    return vstack(crs_arrays).tocoo()

In [66]:
connectivity_matrix = gen_connectivity_matrix(rng.barcode)

In [88]:
from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=3, connectivity= connectivity_matrix, linkage = 'average')

# Average Linkage

In [89]:
cluster.fit(rng.barcode, rng.y.reshape(-1, 1))

/Users/gradcheckout/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_agglomerative.py:549: UserWarning: the number of connected components of the connectivity matrix is 8 > 1. Completing it to avoid stopping the tree early.
  connectivity, n_connected_components = _fix_connectivity(


AgglomerativeClustering(connectivity=<1000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 194502 stored elements in COOrdinate format>,
                        linkage='average', n_clusters=3)

In [90]:
df = pd.DataFrame(zip(rng.barcode.reshape(-1), cluster.labels_), columns = ['full','reduced'])
df.groupby('full').agg(np.mean)

reduced
full         
0         2.0
1         2.0
2         0.0
3         0.0
4         0.0
5         0.0
6         1.0
7         1.0

# Ward Linkage

In [86]:
df = pd.DataFrame(zip(rng.barcode.reshape(-1), cluster.labels_), columns = ['full','reduced'])

In [87]:
df.groupby('full').agg(np.mean)

reduced
full         
0         0.0
1         0.0
2         0.0
3         0.0
4         2.0
5         2.0
6         1.0
7         1.0